import type { Metadata } from "next";
import { Maven_Pro } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Analytics } from "@vercel/analytics/next";

const mavenSans = Maven_Pro({
  variable: "--font-maven",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mavenSans.variable} font-sans antialiased`}>
        <Header />
        <div className="pt-20">{children}</div>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
